language: go
go:
  - 1.12
  - 1.13
  - tip

env:
  GO111MODULE=on

install:
  - go get -v -t
  - go get -v github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race